### ISSUE TITLE
Deploy some templates for development purposes

### ISSUE THREAD

**Issue by Pedro-vk** [oceanprotocol/keeper-contracts#400] opened 2019-02-28 15:49 UTC
Could be a good idea to deploy some templates like `EscrowAccessSecretStoreTemplate` for development purposes.

**Comment by ssallam** [comment] 2019-02-28 16:23
The template is `deployed`, what is necessary is to have it `approved` as part of the keeper-contracts deployment process. And for now, we only need the one template `
EscrowAccessSecretStoreTemplate`.

**Comment by H34D** [comment] 2019-03-06 07:26
duplicate of #264

**Closed** 2019-03-06 07:26 UTC
