### ISSUE TITLE
Truffle migrating

### ISSUE THREAD

**Issue by prostiak** [oceanprotocol/keeper-contracts#82] opened 2018-08-28 16:47 UTC
Running migration: 4_deploy_plcr.js
  Linking DLL to PLCRVoting
  Linking AttributeStore to PLCRVoting
  Deploying PLCRVoting...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: PLCRVoting contains unresolved libraries. You must deploy and link the following libraries before you can deploy a new version of PLCRVoting: 

Your Get started Guide dont't work. This is an error while migrating in truffle. Can you create normal,readble and working guide ? The community can't test your product, because you need to test it first. Right now it is sad. P.S. Can't touch your product in local network, the same thing in https://kovan.etherscan.io/address/0x2c0d5f47374b130ee398f4c34dbe8168824a8616. Can we have some testnet ???

**Comment by H34D** [comment] 2018-08-29 06:19
Hello @prostiak,

what node are you trying migrating to? It looks like that your blockchain node is not in a healthy state (`Error encountered, bailing. Network state unknown. Review successful transactions manually.`). 

We have a testnet running on `kovan`. The address `0x2c0d5f47374b130ee398f4c34dbe8168824a8616` is the address we deploy contracts from and has nothing to do with the contracts itself. 

You can find the addresses of the `kovan` contracts in the readme. If you want to use the `ABI`'s directly you can find the latest version of the `kovan` `ABI`'s and addresses in the `artifacts` folder of the repo.

**Comment by prostiak** [comment] 2018-08-29 07:04
Again. I am using your step by step Guide. Inside we use ganache-cli. Did you test it (the Guide) ? As you can see migrating have an error on the 4-th step , not in the node. "Linking DLL to PLCRVoting
Linking AttributeStore to PLCRVoting". PLCRVoting is your contract, and DLL is the library insight, as I see. How we can touch your product, if we have problems at the begining ?  Your contract in Kovan is your creation. I don't know what you have in the backyard. So it would be great, if we (developers) could test your product localy. But as you can see we have a problems at the begining. And i am not the only one, so you can think this is a collective issue. No chance to test your product === no chance to say it good (i hope it is).

**Comment by aaitor** [comment] 2018-08-29 07:54
Thanks for your feedback @prostiak, I just run the step by step guide in a totally clean environment and worked properly. Also, this testing is automated in the CI environment.

Using your description of the problem looks the dependency of the PLCRVoting (DLL), was not deployed in your blockchain node. 

Please, can you indicate the version of ganache-cli and node.js you are using?
Can you paste the complete output and command executed?
What is your system configuration? Win, Linux or Mac?

Having this we can try to reproduce or identify where is the problem.

In the meantime, you can use the docker image to integrate your application with the Smart Contracts:
https://hub.docker.com/r/oceanprotocol/keeper-contracts/

**Comment by prostiak** [comment] 2018-08-29 08:33
Ubuntu 16.04, Truffle v4.1.14 (core: 4.1.14), Solidity v0.4.24 (solc-js), Ganache CLI v6.1.8 (ganache-core: 2.2.1), Node Js v9.11.2. All comands used through the Get Started Guide: 
git clone git@github.com:oceanprotocol/keeper-contracts.git
cd keeper-contracts/
npm i
truffle compile
ganache-cli  (in new terminal)
truffle migrate... And then we have a problem. My colleague has the same.

**Comment by milkyklim** [comment] 2018-08-29 09:16
I might have a related problem. 

If I follow the guide at the `truffle compile` step I get: 

`Error: Cannot find module './build/Release/scrypt’`. 

But if I run `npm install @oceanprotocol/keeper-contracts` everything works like a charm. 

Was running the code on Ubuntu 16.04.4 LTS, with node v8.11.4.

**Comment by H34D** [comment] 2018-08-29 09:55
The error was reproducible by playing around with async/await in truffle migrate scripts. I have added a hotfix branch including a PR (https://github.com/oceanprotocol/keeper-contracts/pull/83) @prostiak @milkyklim please checkout that branch and test if this fixes your issue.

**Comment by H34D** [comment] 2018-08-31 07:11
#83 merged, closing issue

**Closed by H34D** 2018-08-31 07:11 UTC
Labels: bug
